### ISSUE TITLE
Create interactive screens (prototyping)

### ISSUE THREAD

**Issue by mackmcg** [FAMU-CIS-Library/CISMOLibrary#2]

**Comment by ftripjr** [comment]
Remember to check [figma](https://www.figma.com/)

**Comment by ftripjr** [comment]
If you need assets @mackmcg, check [this link].(https://iconmonstr.com/)

**Comment by mackmcg** [comment]
https://www.figma.com/file/Aj3OuURTsaMWxV2pIsVtCr/CIS-Library?node-id=0%3A1

^interactive prototype

**Comment by ftripjr** [comment]
Does figma have share functionality? using a share link may be better

**Comment by mackmcg** [comment]
https://www.figma.com/file/Aj3OuURTsaMWxV2pIsVtCr/CIS-Library?node-id=0%3A1

try it with this link

**Comment by ftripjr** [comment]
[The link](https://www.figma.com/file/Aj3OuURTsaMWxV2pIsVtCr/CIS-Library?node-id=0%3A1) you gave is working perfectly!

**Comment by ftripjr** [comment]
@mackmcg if you're having issues finding things to do in the 2nd milestone, I suggest coming back to this ticket first and making transistions on in the wireframe. If you can record them afterwards, we'd need that as well. If not, I can record the wireframe on my PC once you complete adding this transistions. If you need help with that, [I recommend using this tutorial on prototyping with transistions.](https://www.figma.com/blog/figma-prototyping-now-with-transitions/)
